-- Restaurant seating tables and booking table assignment.
-- Tables are admin-managed; staff read/write them via RLS and assign table_id on bookings.

create table if not exists public.tables (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  restaurant_id bigint not null,
  pax_max smallint null,
  name text not null,
  constraint tables_pkey primary key (id),
  constraint tables_restaurant_id_fkey foreign key (restaurant_id) references restaurants (id)
);

create index if not exists idx_tables_restaurant_id on public.tables (restaurant_id);

alter table public.tables enable row level security;

-- Staff may read tables for their assigned restaurant only.
drop policy if exists tables_select_own_restaurant on public.tables;
create policy tables_select_own_restaurant
  on public.tables for select
  using (
    restaurant_id = (select restaurant_id from public.profiles where id = auth.uid())
  );

-- Staff may manage tables for their assigned restaurant (admin page).
drop policy if exists tables_insert_own_restaurant on public.tables;
create policy tables_insert_own_restaurant
  on public.tables for insert
  with check (
    restaurant_id = (select restaurant_id from public.profiles where id = auth.uid())
  );

drop policy if exists tables_update_own_restaurant on public.tables;
create policy tables_update_own_restaurant
  on public.tables for update
  using (
    restaurant_id = (select restaurant_id from public.profiles where id = auth.uid())
  )
  with check (
    restaurant_id = (select restaurant_id from public.profiles where id = auth.uid())
  );

drop policy if exists tables_delete_own_restaurant on public.tables;
create policy tables_delete_own_restaurant
  on public.tables for delete
  using (
    restaurant_id = (select restaurant_id from public.profiles where id = auth.uid())
  );

-- Link bookings to a seating table (nullable; assigned at create/edit time).
alter table public.bookings
  add column if not exists table_id bigint references public.tables (id);

create index if not exists idx_bookings_table_id on public.bookings (table_id);
