-- Restaurant seating tables.
-- Tables are admin-managed; staff read them via RLS and assign table_id on bookings.

create table if not exists public.tables (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  restaurant_id bigint not null,
  pax_max smallint null,
  name text not null,
  constraint tables_pkey primary key (id),
  constraint tables_restaurant_id_fkey foreign key (restaurant_id) references restaurants (id)
);

create index if not exists idx_tables_restaurant_id on public.tables (restaurant_id);

alter table public.tables enable row level security;

-- Staff may read tables for their assigned restaurant only.
drop policy if exists tables_select_own_restaurant on public.tables;
create policy tables_select_own_restaurant
  on public.tables for select
  using (
    restaurant_id = (select restaurant_id from public.profiles where id = auth.uid())
  );
